### ISSUE TITLE
Update bricked machine

### ISSUE THREAD

**Issue by TEJLJR** [jacklukem/CatalinaOTAswufix#1]
I updated to Catalina 10.15.7 (19H114) on my MacBook Pro 7,1, which includes Security Update 2020-001. I tried to repatch my system and it failed. This isn't the first time a software update using your tool has bricked my machine. This happened with 10.15.7 (19H2) as well. Everytime I repatch and it reboots, it just gets stuck on the boot screen and does nothing. The progress bar just moves, but my machine doesn't go to the login screen.

**Comment by jacklukem** [comment]
It doesn't bricked, maybe just software soft brick during the staged installer, that in most cases is due to SIP and AMFI enabled due to pram reset, in that case you could easily boot from my customised opencore setup either to continue the hidden "macOS Installer" or after installation completes even to boot macOS without any patches: [USBOpenCoreAPFSloader3](https://github.com/jacklukem/USBOpenCoreAPFSloader/releases/download/3.0/USBOpenCoreAPFSloader3.app.zip)
